### ISSUE TITLE
Equality for Set

### ISSUE THREAD

**Issue by ivanperez-keera** [jfdm/idris-containers#30]
Hi

I don't understand why equality, as currently defined for sets, would work at all. It seems to only act on the head.

If my point is correct, then how would you go at defining it? In particular, I'm trying to prove that the union of two sets built from lists using `fromList` is the same as another set built using `fromList`, by means of list permutations, but without much success.

**Comment by jfdm** [comment]
@ivanperez-keera @ahmadsalim added the implementations, and tbh haven't looked to much at them. If you think there are serious issues, then PRs are welcome.

**Comment by ivanperez-keera** [comment]
@jfdm Thanks.

@ahmadsalim Do you know?

I'm talking about this:

https://github.com/jfdm/idris-containers/blob/master/Data/AVL/Set.idr#L68-L69

**Comment by ahmadsalim** [comment]
@ivanperez-keera Yes, because `Element` is a constructor of `Subset A P`, which contains two elements the first which come from A` and the second is a proof that they all satisfy `P`.

In our implementation (https://github.com/jfdm/idris-containers/blob/master/Data/AVL/Tree.idr#L109) the first element contains the underlying tree representing the elements and the second is a proof that the tree satisfies the required invariants. Basically we just drop the invariant in the comparison and rely on tree equality which is implemented in https://github.com/jfdm/idris-containers/blob/master/Data/AVL/Tree.idr#L332 .

If you find that tree equality is not sufficient because balancing reshuffled the elements, one can consider simply flattening the list preorder and comparing the elements.
